name    'puppetlabs-openstack'
version '3.0.0'
source  'https://github.com/stackforge/puppet-openstack'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Openstack Module targeted for Havana'
description 'Puppet module that pulls together all the individual components of Openstack, resulting is a complete and functional stack.'
project_page 'https://github.com/stackforge/puppet-openstack'

dependency 'puppetlabs/glance', '>= 3.1.0 <4.0.0'
dependency 'puppetlabs/horizon', '>= 3.1.0 <4.0.0'
dependency 'puppetlabs/keystone', '>= 3.2.0 <4.0.0'
dependency 'puppetlabs/nova', '>= 3.2.1 <4.0.0'
dependency 'puppetlabs/cinder', '>= 3.1.1 <4.0.0'
dependency 'puppetlabs/swift', '>= 3.0.0 <4.0.0'
dependency 'puppetlabs/neutron', '>= 3.3.0 <4.0.0'
dependency 'puppetlabs/ceilometer', '>= 3.1.1 <4.0.0'
dependency 'puppetlabs/heat', '>= 3.1.0 <4.0.0'

dependency 'puppetlabs/ntp',         '>=3.3.0 <4.0.0'
dependency 'puppetlabs/firewall',    '>=1.7.1 <2.0.0'
dependency 'puppetlabs/vswitch',     '>=0.3.0 <1.0.0'
dependency 'puppetlabs/mongodb',     '>=0.11.0 <1.0.0'
